library(sf)
minimal_line <- sf::st_sf(a = 1:3,
                          geometry = sf::st_sfc(
                            sf::st_linestring(cbind(c(0, 0.5, 1), c(0,0, 0))),
                            sf::st_linestring(cbind(c(0.5, 1, 1), c(0, 0, 0.5))),
                            sf::st_linestring(cbind(c(0, 1), c(1, 1)))))




class(minimal_line$geometry) <- c("sfc_LINESTRING", "sfc" , "list")
raw_chars <- c(LETTERS, letters, 0:9)
viridis_cols <- viridis::viridis(256)

arc0 <- structure(list(object = structure(list(ID = 9897:9899, GAR_ID = c(0L,
                                                                          0L, 0L), Name = c(NA, NA, NA), ShortLabel = c(15L, 26L, 16L),
                                               LongLabel = c(NA, NA, NA), StartDate = c(NA, NA, NA), EndDate = c(NA,
                                                                                                                 NA, NA), Descr = c(NA, NA, NA), Reference = c(NA, NA, NA),
                                               ParentID = c(0L, 0L, 0L), CreatedBy = c(NA, NA, NA), CreatedOn = c(NA,
                                                                                                                  NA, NA), ModifiedBy = c(NA, NA, NA), ModifiedOn = c(NA, NA,
                                                                                                                                                                      NA), object_ = c("fDA4NR", "XiqHcC", "Fde0oG")), row.names = c(NA,
                                                                                                                                                                                                                                     -3L), class = c("tbl_df", "tbl", "data.frame")), object_link_arc = structure(list(
                                                                                                                                                                                                                                       object_ = c("fDA4NR", "Fde0oG", "fDA4NR", "Fde0oG", "XiqHcC",
                                                                                                                                                                                                                                                   "fDA4NR"), arc_ = c("14gHCT", "BzW58t", "G3aVCZ", "HXhhhZ",
                                                                                                                                                                                                                                                                       "Kw6tnA", "qbAzWr")), class = c("tbl_df", "tbl", "data.frame"
                                                                                                                                                                                                                                                                       ), row.names = c(NA, -6L)), arc_link_vertex = structure(list(
                                                                                                                                                                                                                                                                         arc_ = c("14gHCT", "14gHCT", "14gHCT", "14gHCT", "14gHCT",
                                                                                                                                                                                                                                                                                  "14gHCT", "14gHCT", "14gHCT", "14gHCT", "14gHCT", "14gHCT",
                                                                                                                                                                                                                                                                                  "14gHCT", "14gHCT", "14gHCT", "14gHCT", "14gHCT", "14gHCT",
                                                                                                                                                                                                                                                                                  "14gHCT", "14gHCT", "14gHCT", "14gHCT", "14gHCT", "14gHCT",
                                                                                                                                                                                                                                                                                  "14gHCT", "14gHCT", "BzW58t", "BzW58t", "BzW58t", "BzW58t",
                                                                                                                                                                                                                                                                                  "BzW58t", "BzW58t", "G3aVCZ", "G3aVCZ", "HXhhhZ", "HXhhhZ",
                                                                                                                                                                                                                                                                                  "HXhhhZ", "HXhhhZ", "HXhhhZ", "HXhhhZ", "HXhhhZ", "HXhhhZ",
                                                                                                                                                                                                                                                                                  "HXhhhZ", "HXhhhZ", "HXhhhZ", "HXhhhZ", "HXhhhZ", "HXhhhZ",
                                                                                                                                                                                                                                                                                  "HXhhhZ", "HXhhhZ", "HXhhhZ", "HXhhhZ", "HXhhhZ", "HXhhhZ",
                                                                                                                                                                                                                                                                                  "HXhhhZ", "HXhhhZ", "HXhhhZ", "HXhhhZ", "HXhhhZ", "HXhhhZ",
                                                                                                                                                                                                                                                                                  "HXhhhZ", "HXhhhZ", "HXhhhZ", "Kw6tnA", "Kw6tnA", "qbAzWr",
                                                                                                                                                                                                                                                                                  "qbAzWr", "qbAzWr", "qbAzWr"), vertex_ = c("Wk5Kq0", "wbynLI",
                                                                                                                                                                                                                                                                                                                             "51q4NY", "HRS0PG", "FUVsDN", "cpHFsI", "ktc9ji", "j5Wgai",
                                                                                                                                                                                                                                                                                                                             "NEhsmN", "H9XjwF", "uTiXw1", "ZEWXCv", "MxAD8s", "rgCIhQ",
                                                                                                                                                                                                                                                                                                                             "7wskTL", "5jwfJQ", "Le3LiV", "Z3sAyj", "UDoJlL", "ObmLOH",
                                                                                                                                                                                                                                                                                                                             "TUQ0q8", "mGmsGs", "36bowK", "DQZU3r", "nh7u3z", "KqPxWi",
                                                                                                                                                                                                                                                                                                                             "8iaPdq", "J9ikST", "gqZfTn", "ugDT2T", "OSdzZE", "nh7u3z",
                                                                                                                                                                                                                                                                                                                             "OSdzZE", "nh7u3z", "zWVMb5", "1BCUmE", "A626py", "d0cUt6",
                                                                                                                                                                                                                                                                                                                             "LoaVUG", "oRaCXR", "6omq7z", "jyIhuM", "VrQUmc", "MdKD3M",
                                                                                                                                                                                                                                                                                                                             "70cyDP", "u9wfQw", "qS10ft", "SlFVXb", "TaiOhG", "c4netf",
                                                                                                                                                                                                                                                                                                                             "ema3bm", "83V0fh", "O2rheZ", "bCgNB3", "jkDjEw", "gWLkgK",
                                                                                                                                                                                                                                                                                                                             "j2WrX3", "FhmIyB", "f4o2FT", "LR51RL", "z49XzO", "KqPxWi",
                                                                                                                                                                                                                                                                                                                             "Wk5Kq0", "KqPxWi", "OSdzZE", "uHnzDn", "ybaDYc", "Wk5Kq0"
                                                                                                                                                                                                                                                                                  )), row.names = c(NA, -68L), class = c("tbl_df", "tbl", "data.frame"
                                                                                                                                                                                                                                                                                  )), vertex = structure(list(x_ = c(-50, -37.1219090007997, -37.1219090007997,
                                                                                                                                                                                                                                                                                                                     -37.2692320002566, -37.6215520004245, -37.7696440002704, -37.9175370008319,
                                                                                                                                                                                                                                                                                                                     -38.0643150003369, -38.2090640007031, -38.3092820006637, -38.4289220005499,
                                                                                                                                                                                                                                                                                                                     -38.7096161213868, -38.8998170000544, -39.027836000531, -39.1494939999481,
                                                                                                                                                                                                                                                                                                                     -39.263995000269, -39.3705740003898, -39.4685100003362, -39.557121000134,
                                                                                                                                                                                                                                                                                                                     -39.6357770004082, -39.7039010006307, -39.7609720001577, -39.8065330003976,
                                                                                                                                                                                                                                                                                                                     -39.8401960005449, -39.861642000278, -39.8706320002665, -39.8712290121025,
                                                                                                                                                                                                                                                                                                                     -50, -39.872459, -39.8723950006287, -37.135, -37.2669820008187,
                                                                                                                                                                                                                                                                                                                     -37.349171, -37.469231, -37.627623, -37.7332040006641, -37.8280740004147,
                                                                                                                                                                                                                                                                                                                     -38.019543000509, -38.167383, -38.3095550006627, -38.4450239999999,
                                                                                                                                                                                                                                                                                                                     -38.579282, -38.658221, -38.8040589999999, -38.944037, -39.0771400007104,
                                                                                                                                                                                                                                                                                                                     -39.202414, -39.3189770005881, -39.426027, -39.5228430004041,
                                                                                                                                                                                                                                                                                                                     -39.6087910006041, -39.6833300007789, -39.74601, -39.796477000713,
                                                                                                                                                                                                                                                                                                                     -39.834471, -39.8598229999999, -50, -37.135, -41, -44.7611380005183
                                                                                                                                                                                                                                                                                  ), y_ = c(-49.9999999967314, -50, -52.8392119968708, -52.8269459968924,
                                                                                                                                                                                                                                                                                            -52.816152997393, -52.8121459969695, -52.8158009973482, -52.8270949974685,
                                                                                                                                                                                                                                                                                            -52.8459599968922, -52.8608239970686, -52.8779709973058, -52.9336277157992,
                                                                                                                                                                                                                                                                                            -52.9853799970519, -53.0327339972479, -53.0866279968665, -53.1467189971773,
                                                                                                                                                                                                                                                                                            -53.2126279968901, -53.2839349973211, -53.3601819971343, -53.4408789971157,
                                                                                                                                                                                                                                                                                            -53.5255009973362, -53.6134939974288, -53.7042809968655, -53.7972569974238,
                                                                                                                                                                                                                                                                                            -53.891801997492, -53.9872779973259, -53.9999919812002, -54,
                                                                                                                                                                                                                                                                                            -54.1151399977676, -54.0193959972772, -55.8486999169021, -55.7922189979331,
                                                                                                                                                                                                                                                                                            -55.7517079980204, -55.6850849980111, -55.5855449979969, -55.512562997769,
                                                                                                                                                                                                                                                                                            -55.434618997942, -55.3594419980123, -55.3227499979587, -55.2786649979419,
                                                                                                                                                                                                                                                                                            -55.2275169979446, -55.1813459979376, -55.1523089979332, -55.1139799979275,
                                                                                                                                                                                                                                                                                            -55.0683249979205, -55.0156839978293, -54.9564469979035, -54.8910499978509,
                                                                                                                                                                                                                                                                                            -54.8199739978823, -54.7437369979329, -54.6628919974237, -54.5780219974596,
                                                                                                                                                                                                                                                                                            -54.4897339978297, -54.3986549978432, -54.3054269977995, -54.2107029977838,
                                                                                                                                                                                                                                                                                            -56.9999999984136, -57, -57, -57), vertex_ = c("uHnzDn", "ybaDYc",
                                                                                                                                                                                                                                                                                                                                           "Wk5Kq0", "wbynLI", "51q4NY", "HRS0PG", "FUVsDN", "cpHFsI", "ktc9ji",
                                                                                                                                                                                                                                                                                                                                           "j5Wgai", "NEhsmN", "H9XjwF", "uTiXw1", "ZEWXCv", "MxAD8s", "rgCIhQ",
                                                                                                                                                                                                                                                                                                                                           "7wskTL", "5jwfJQ", "Le3LiV", "Z3sAyj", "UDoJlL", "ObmLOH", "TUQ0q8",
                                                                                                                                                                                                                                                                                                                                           "mGmsGs", "36bowK", "DQZU3r", "nh7u3z", "OSdzZE", "1BCUmE", "zWVMb5",
                                                                                                                                                                                                                                                                                                                                           "KqPxWi", "z49XzO", "LR51RL", "f4o2FT", "FhmIyB", "j2WrX3", "gWLkgK",
                                                                                                                                                                                                                                                                                                                                           "jkDjEw", "bCgNB3", "O2rheZ", "83V0fh", "ema3bm", "c4netf", "TaiOhG",
                                                                                                                                                                                                                                                                                                                                           "SlFVXb", "qS10ft", "u9wfQw", "70cyDP", "MdKD3M", "VrQUmc", "jyIhuM",
                                                                                                                                                                                                                                                                                                                                           "6omq7z", "oRaCXR", "LoaVUG", "d0cUt6", "A626py", "ugDT2T", "8iaPdq",
                                                                                                                                                                                                                                                                                                                                           "J9ikST", "gqZfTn")), class = c("tbl_df", "tbl", "data.frame"
                                                                                                                                                                                                                                                                                                                                           ), row.names = c(NA, -60L)), meta = structure(list(proj = "+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0",
                                                                                                                                                                                                                                                                                                                                                                                              ctime = "2019-10-30 22:46:56"), row.names = c(NA, -1L), class = c("tbl_df",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                "tbl", "data.frame"))), class = c("ARC", "sc"), join_ramp = c("object",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              "object_link_arc", "arc_link_vertex", "vertex"))

raw_chars <- c(LETTERS, letters, 0:9)
viridis_cols <- viridis::viridis(256)
.xyz <-   sf::st_sfc(sf::st_linestring(cbind(c(0, 0, 1, 1, 0),
                                                    c(0, 1, 1, 0, 0),
                                                    rnorm(4)[c(1, 2, 3, 4, 1)])) )

.tr <- trip::walrus818[600:1200, ]
.cad_tas_path0 <- PATH0(anglr::cad_tas)
usethis::use_data(.cad_tas_path0, .tr, .xyz, viridis_cols,raw_chars,minimal_line, arc0, internal = TRUE, overwrite = TRUE)
